version: '3'

vars:
  OS_TYPE: '{{if eq .OS "windows"}}windows{{else}}unix{{end}}'
  CLEAR_CMD: '{{if eq .OS "windows"}}cls{{else}}clear{{end}}'
  NO_OUTPUT: '{{if eq .OS "windows"}}> nul{{else}}> /dev/null{{end}}'

tasks:
  debug:
    desc: Start development server
    cmds:
      - cmd: '{{.CLEAR_CMD}}'
      - cmd: cargo tauri dev

  release:
    desc: Platform-appropriate release build
    cmds:
      - cmd: '{{.CLEAR_CMD}}'
      - cmd: |
          {{if eq .OS "windows" -}}
          cargo tauri build --target x86_64-pc-windows-msvc --verbose
          {{- else -}}
          MACOSX_DEPLOYMENT_TARGET=11.0 cargo tauri build --target universal-apple-darwin --verbose
          {{- end}}

  release-macos:
    desc: Universal macOS build (requires Darwin)
    platform: darwin
    cmds:
      - cmd: '{{.CLEAR_CMD}}'
      - cmd: MACOSX_DEPLOYMENT_TARGET=11.0 cargo tauri build --target universal-apple-darwin --verbose

  release-windows:
    desc: Windows production build
    cmds:
      - cmd: '{{.CLEAR_CMD}}'
      - cmd: cargo tauri build --target x86_64-pc-windows-msvc --verbose

  release-macos-production:
    desc: Signed macOS build
    platform: darwin
    cmds:
      - cmd: |
          MACOSX_DEPLOYMENT_TARGET=11.0 \
          APPLE_SIGNING_IDENTITY="Developer ID Application: Öner Efe Dasguney (C4G7YDX6RS)" \
          cargo tauri build --target universal-apple-darwin --verbose

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: echo Removing build artifacts...
      - cmd: cd ./src-tauri && cargo clean {{.NO_OUTPUT}}

