[package]
name = "bmm-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
home = "0.5.9"
libflate = "2.1.0"
libloading = "0.8.6"
log = "0.4.22"
rusqlite = { version = "0.32.1", features = ["bundled"] }
sysinfo = "0.33.0"
zip = "2.2.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
tasklist = "0.2.15"

[target.'cfg(unix)'.dependencies]
libproc = "0.14.10"

[build-dependencies]
dirs = "5.0.1"
