[package]
name = "bmm-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
home = "0.5.9"
libflate = "2.1.0"
libloading = "0.8.6"
log = "0.4.22"
rusqlite = "0.32.1"
zip = "2.2.1"

[build-dependencies]
dirs = "5.0.1"
