[package]
name = "bmm-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
dirs = "6.0.0"
flate2 = { version = "1.0.35", features = ["zlib"] }
home = "0.5.11"
infer = "0.16.0"
libflate = "2.1.0"
libloading = "0.8.6"
log = "0.4.25"
reqwest = { version = "0.12.12", features = ["json"] }
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_repr = "0.1.19"
tar = "0.4.43"
tokio = { version = "1.43.0", features = ["full"] }
zip = "2.2.2"

[dev-dependencies]
tempfile = "3.16.0"
scopeguard = "1.2.0"
mockito = "1.6.1"
tokio = { version = "1.43.0", features = ["full", "test-util"] }
rstest = "0.24.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
tasklist = "0.2.15"

[target.'cfg(unix)'.dependencies]
libproc = "0.14.10"

[build-dependencies]
dirs = "6.0.0"
